### ISSUE TITLE
Conjuntos y relaciones

### ISSUE THREAD

**Issue by 00Asaf00** [SistemasTecTlaxiaco/actividad-4-mapa-mental-00Asaf00#3]
[Conjuntos y relaciones.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-00Asaf00/files/12674193/Conjuntos.y.relaciones.pdf)

[Conjuntos y relaciones.png](https://drive.google.com/file/d/1c8FxHrHMqsMKQhHh9Ch9uSF3dN8sOLW3/view?usp=sharing)

**Comment by elisa1223** [comment]
Manejo conceptual y dominio del tema 25%
Relacion entre los conceptos incluidos en el mapa 25%
Calidad de la presentación 25%
Jerarquía 25%

Calificación 20 / 20
Evaluado por el quipo de Elisa Sánchez Coronel

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
